apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: product
  namespace: canary-demo

spec:
  replicas: 4

  strategy:
    canary:
      canaryService: product-canary
      stableService: product-stable

      trafficRouting:
        istio:
          virtualService:
            name: product
            routes:
              - primary

      steps:
        - setWeight: 10
        - pause: {}
        - setWeight: 30
        - pause: {}
        - setWeight: 50
        - pause: {}
        - setWeight: 70
        - pause: {}
        - setWeight: 100

  selector:
    matchLabels:
      app: product

  template:
    metadata:
      labels:
        app: product

    spec:
      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: product

          image: ghcr.io/rsy2022p/istio-argo-canary-demo:product-23f104b

          imagePullPolicy: IfNotPresent

          env:
            - name: VERSION
              value: "product-a055f5a"

          ports:
            - name: http
              containerPort: 8080

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10