apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: product
  namespace: canary-demo

spec:
  replicas: 4

  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: product

  template:
    metadata:
      labels:
        app: product

    spec:
      containers:
        - name: product

          image: product:v3

          imagePullPolicy: IfNotPresent

          env:
            - name: VERSION
              value: "v3"

          ports:
            - name: http
              containerPort: 8080

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10

  strategy:

    canary:

      stableService: product-stable

      canaryService: product-canary

      trafficRouting:
        istio:
          virtualService:
            name: product
            routes:
              - primary

      steps:

        - setWeight: 10

        - pause:
            duration: 30s

        - setWeight: 30

        - pause:
            duration: 30s

        - setWeight: 50

        - pause:
            duration: 30s

        - setWeight: 100
