name: Build and Push Product Image

on:
  push:
    branches:
      - main
    paths:
      - "app/**"

permissions:
  contents: write
  packages: write

jobs:
  build-push:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image variables
        run: |
          echo "IMAGE=ghcr.io/${{ github.repository }}" >> "$GITHUB_ENV"
          echo "TAG=product-${GITHUB_SHA::7}" >> "$GITHUB_ENV"

      - name: Build Docker image
        run: |
          docker build \
            -t "${IMAGE}:${TAG}" \
            ./app

      - name: Push Docker image
        run: |
          docker push "${IMAGE}:${TAG}"

      - name: Update rollout manifest
        run: |
          sed -i \
            "s|^[[:space:]]*image:.*|          image: ${IMAGE}:${TAG}|" \
            k8s/rollout.yaml

          sed -i \
            "s|value: \"v[^\"]*\"|value: \"${TAG}\"|" \
            k8s/rollout.yaml

          echo "Updated image:"
          grep "image:" k8s/rollout.yaml

          echo "Updated VERSION:"
          grep -A1 "name: VERSION" k8s/rollout.yaml

      - name: Commit manifest
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add k8s/rollout.yaml

          if git diff --cached --quiet; then
            echo "No manifest changes"
          else
            git commit -m "Deploy ${TAG}"
            git push
          fi